version: '3.8'


services:
  backend:
    build: ./backend
    command:
      - uvicorn
      - config.asgi:application
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    volumes:
      - backend_data:/src/db

  frontend:
    build: ./frontend
    container_name: angular-app
    volumes:
      - ./:/angular-app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  backend_data:
