version: "3.9"

services:
  backend:
    build: ./backend
    command:
      - uvicorn
      - config.asgi:application
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    ports:
      - "8080:8000"
